import { CryptoCoin, StakingPlan } from './types';
import { Zap, TrendingUp, Trophy } from 'lucide-react';

export const MOCK_COINS: CryptoCoin[] = [
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    price: 64231.45,
    change24h: 2.34,
    marketCap: '$1.2T',
    volume: '$32B',
    data: [62000, 62500, 61800, 63000, 63500, 64231],
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    price: 3452.12,
    change24h: 1.12,
    marketCap: '$400B',
    volume: '$15B',
    data: [3300, 3350, 3320, 3400, 3420, 3452],
  },
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    price: 145.67,
    change24h: -0.45,
    marketCap: '$65B',
    volume: '$4B',
    data: [148, 147, 146, 145, 146, 145],
  },
  {
    id: 'bnb',
    name: 'BNB',
    symbol: 'BNB',
    price: 590.20,
    change24h: 0.12,
    marketCap: '$87B',
    volume: '$1.2B',
    data: [585, 588, 587, 592, 591, 590],
  },
  {
    id: 'cardano',
    name: 'Cardano',
    symbol: 'ADA',
    price: 0.45,
    change24h: 5.67,
    marketCap: '$16B',
    volume: '$800M',
    data: [0.41, 0.42, 0.43, 0.44, 0.44, 0.45],
  },
  {
    id: 'ripple',
    name: 'XRP',
    symbol: 'XRP',
    price: 0.62,
    change24h: 0.89,
    marketCap: '$34B',
    volume: '$1.2B',
    data: [0.60, 0.61, 0.61, 0.62, 0.61, 0.62],
  },
  {
    id: 'dogecoin',
    name: 'Dogecoin',
    symbol: 'DOGE',
    price: 0.16,
    change24h: -2.31,
    marketCap: '$23B',
    volume: '$2.1B',
    data: [0.17, 0.16, 0.16, 0.15, 0.16, 0.16],
  },
  {
    id: 'polkadot',
    name: 'Polkadot',
    symbol: 'DOT',
    price: 7.20,
    change24h: -1.20,
    marketCap: '$10B',
    volume: '$250M',
    data: [7.4, 7.3, 7.2, 7.2, 7.1, 7.2],
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    symbol: 'AVAX',
    price: 36.50,
    change24h: 4.50,
    marketCap: '$13B',
    volume: '$600M',
    data: [34, 35, 34, 36, 36, 36.5],
  },
  {
    id: 'chainlink',
    name: 'Chainlink',
    symbol: 'LINK',
    price: 14.20,
    change24h: 0.50,
    marketCap: '$8B',
    volume: '$300M',
    data: [14, 14.1, 14.2, 14.1, 14.3, 14.2],
  },
  {
    id: 'shiba',
    name: 'Shiba Inu',
    symbol: 'SHIB',
    price: 0.000025,
    change24h: 8.40,
    marketCap: '$14B',
    volume: '$900M',
    data: [0.000022, 0.000023, 0.000024, 0.000024, 0.000025, 0.000025],
  },
  {
    id: 'near',
    name: 'NEAR Protocol',
    symbol: 'NEAR',
    price: 6.80,
    change24h: 3.20,
    marketCap: '$7B',
    volume: '$450M',
    data: [6.5, 6.6, 6.7, 6.6, 6.8, 6.8],
  }
];

export const STAKING_PLANS: StakingPlan[] = [
  {
    id: 'flexible',
    name: 'Flexible Saver',
    apy: 5.5,
    duration: 'Flexible',
    durationDays: 30,
    minStake: 50,
    poolFilled: 45,
    participants: 12403,
    features: ['Instant Withdrawals', 'Daily Compound Interest', 'No Locking Period', 'Auto-Reinvest'],
    color: 'text-emerald-400',
    icon: Zap,
    gradient: 'from-emerald-500 to-teal-500',
    shadow: 'shadow-emerald-500/20',
    risk: 'Low',
    description: 'The safest way to grow your portfolio. Ideal for traders who need liquidity while earning passive income.',
    faq: [
      { q: "Can I withdraw anytime?", a: "Yes, funds in Flexible Saver are available for withdrawal 24/7 without penalty." },
      { q: "How is interest paid?", a: "Interest is calculated daily at 00:00 UTC and added to your balance." }
    ]
  },
  {
    id: 'growth',
    name: 'Growth Vault',
    badge: 'Popular',
    apy: 12.8,
    duration: '30 Days',
    durationDays: 30,
    minStake: 500,
    poolFilled: 82,
    participants: 8392,
    features: ['Capital Protection', 'Multiplier Bonuses', 'Weekly Distributions', 'Priority Support'],
    color: 'text-indigo-400',
    icon: TrendingUp,
    gradient: 'from-indigo-500 to-blue-500',
    shadow: 'shadow-indigo-500/20',
    risk: 'Medium',
    description: 'Strike a balance between flexibility and yield. Lock your assets for a month to unlock higher tier rewards.',
    faq: [
      { q: "What happens if I unstake early?", a: "Early unstaking forfeits all accrued interest and incurs a 2% fee on principal." },
      { q: "Is the APY fixed?", a: "Yes, the 12.8% APY is guaranteed for the duration of the lock." }
    ]
  },
  {
    id: 'genesis',
    name: 'Genesis Elite',
    badge: 'Limited Time',
    apy: 32.4,
    duration: '90 Days',
    durationDays: 90,
    minStake: 2000,
    poolFilled: 94,
    participants: 2104,
    features: ['Maximum Yield', 'VIP Governance Rights', 'Exclusive Airdrops', 'Concierge Service'],
    color: 'text-pink-400',
    icon: Trophy,
    gradient: 'from-purple-500 to-pink-500',
    shadow: 'shadow-pink-500/20',
    risk: 'Medium',
    description: 'For the committed investor. High-yield strategy utilizing DeFi protocols and lending markets.',
    faq: [
      { q: "What is Genesis Elite?", a: "A limited capacity pool offering our highest institutional rates." },
      { q: "Are there risks?", a: "While principal is secured, high yields come from DeFi lending which carries protocol risk. We insure up to 90%." }
    ]
  }
];